--  Auto-generated SQL script #201911071104
UPDATE clv_benefits.bnf_configuracion_clausula
	SET texto='{"legal":{"1":"<p>Rates are commisionable to (Company Name) at @%COMMISSION@&nbsp;%. Please note the commission is calculated on the balance after deducting 3% hostipitality tax and $5.00 USD per persona, per day, for gratuities from the above rates.&nbsp; Commissions will be paid via wire transfer. Please include this information in the invoice.</p><p>Invoices should be issued to:<br>Heron Development Corp.<br>RUC&nbsp;155618202-2-2015 <br>DV-50Torre Generali Piso 19 Av. Samuel Lewis. <br>Panamá, Panamá</p>"},"comercial":{"1":"<p>Rates are commisionable to (Company Name) at (%) @%COMMISSION@ %. Please note the commission is calculated on the balance after deducting 3% hostipitality tax and $5.00 USD per persona, per day, for gratuities from the above rates.</p>"}}'
	WHERE idbnf_configuracion_clausula=1;
UPDATE clv_benefits.bnf_configuracion_clausula
	SET texto='{"legal":{"1":"<p>Rates are commisionable to (Company Name) at&nbsp;@%COMMISSION@% %. Please note the commission is calculated on the balance after deducting $4.00 USD per person, per night for Hospitality Tax, 10% of GCT and 10% per person, per day, for gratuities from the above rates.</p>"},"comercial":{"1":"<p>Rates are commisionable to (Company Name) at @%COMMISSION@%. Please note the commission is calculated on the balance after deducting $4.00 USD per person, per night for Hospitality Tax, 10% of GCT and 10% per person, per day, for gratuities from the above rates.</p>"}}'
	WHERE idbnf_configuracion_clausula=2;
UPDATE clv_benefits.bnf_configuracion_clausula
	SET texto='{"legal":{"1":"<p>Discounted\\n  rooms as staff or complimentary and room upgrades are no commissionable.</p>"},"comercial":{"1":"<p>Discounted\\n  rooms as staff or complimentary and room upgrades are no commissionable.</p>"}}'
	WHERE idbnf_configuracion_clausula=3;
UPDATE clv_benefits.bnf_configuracion_clausula
	SET texto='{"legal":{"1":"<p>The Company will cause the Hotel to provide one complimentary room, single or double occupancy for every&nbsp;@COMPS@ rooms paid nightly.&nbsp; These rooms are all-inclusive.&nbsp; (A mandatory charge of $10.00 USD per person, per night will be charged for complimentary rooms for tax and gratuities.)&nbsp; Maximum of&nbsp;@MAXCOMPS@ rooms.</p>"},"comercial":{"1":"<p>Complimentary Rooms: One Complimentary room, single or double occupancy for every @COMPS@&nbsp;rooms paid&nbsp;nightly.  These rooms are all-inclusive. A mandatory charge of $10.00 USD per person, per night will be charged for complimentary rooms for tax and gratuities, to a maximum of&nbsp;@MAXCOMPS@ rooms.</p>"}}'
	WHERE idbnf_configuracion_clausula=4;
UPDATE clv_benefits.bnf_configuracion_clausula
	SET texto='{"legal":{"1":"<p>The Company will cause the Hotel to provide one complimentary room, single or double occupancy for every&nbsp;@COMPS@ rooms&nbsp;paid in comulative basis nightly.&nbsp; These rooms are all-inclusive.&nbsp; A mandatory charge of $10.00 USD per person, per night will be charged for complimentary rooms for tax and gratuities.&nbsp; Maximum of&nbsp;@MAXCOMPS@ rooms.</p>"},"comercial":{"1":"<p>Complimentary Rooms: One Complimentary room, single or double occupancy for every @COMPS@&nbsp;rooms paid&nbsp;in comulative basis nightly.  These rooms are all-inclusive. A mandatory charge of $10.00 USD per person, per night will be charged for complimentary rooms for tax and gratuities, to a maximum of&nbsp;@MAXCOMPS@ rooms.</p>"}}'
	WHERE idbnf_configuracion_clausula=5;
UPDATE clv_benefits.bnf_configuracion_clausula
	SET texto='{"legal":{"1":"<p>\\n \\n \\n  The Company will cause the Hotel to provide one Staff room at\\n  50% of the Group rate single or double occupancy&nbsp;for every&nbsp;@COMPS@ rooms paid\\n  nightly.&nbsp;Staff rates are applicable 2 nights\\n  prior, 1 night post. Maximum&nbsp;@MAXCOMPS@ rooms.</p>"},"comercial":{"1":"<p>\\n \\n \\n  Staff Rooms: One Staff room at 50% of the Group rate single or\\n  double occupancy&nbsp;for every&nbsp;@COMPS@ rooms paid.&nbsp; Staff rates are applicable 2 nights prior,\\n  1 night post. Maximum&nbsp;@MAXCOMPS@ rooms.</p>"}}'
	WHERE idbnf_configuracion_clausula=6;
UPDATE clv_benefits.bnf_configuracion_clausula
	SET texto='{"legal":{"1":"<p>The Company will cause the Hotel to provide one Staff room at\\n  50% of the Group rate single or double occupancy&nbsp;for every&nbsp;@COMPS@ rooms cumulative basis.&nbsp;Staff rates are applicable 2 nights\\n  prior, 1 night post. Maximum&nbsp;@MAXCOMPS@ rooms.</p>"},"comercial":{"1":"<p>Staff Rooms: One Staff room at 50% of the Group rate single or\\n  double occupancy&nbsp;for every&nbsp;@COMPS@ rooms paid  cumulative basis. Staff rates are applicable 2 nights prior,\\n  1 night post. Maximum&nbsp;@MAXCOMPS@ rooms.&nbsp;</p>"}}'
	WHERE idbnf_configuracion_clausula=7;
UPDATE clv_benefits.bnf_configuracion_clausula
	SET texto='{"legal":{"1":"<p>\\n \\n \\n  The Company will cause the Hotel to provide one Up-Grade to the\\n  next category level available&nbsp;for\\n  every&nbsp;@COMPS@ rooms paid nightly. 2 guests maximum. Maximum @MAXCOMPS@ upgrades.&nbsp;Additional\\n  nights will be at the prevailing rates.</p>"},"comercial":{"1":"<p>\\n \\n \\n  Room Upgrades: One Upgrade to the\\n  next room category available&nbsp;for every&nbsp;@COMPS@&nbsp;rooms paid nightly.&nbsp;2 guests maximum. Maximum&nbsp;@MAXCOMPS@ upgrades.&nbsp;\\n  Additional nights will be at the group rates.</p>"}}'
	WHERE idbnf_configuracion_clausula=8;
UPDATE clv_benefits.bnf_configuracion_clausula
	SET texto='{"legal":{"1":"<p>The Company will cause the Hotel to provide one Up-Grade to the\\n  next category level available&nbsp;for\\n  every&nbsp;@COMPS@ rooms paid cumulative basis nightly. 2 guests maximum. Maximum @MAXCOMPS@ upgrades.&nbsp;Additional\\n  nights will be at the prevailing rates.</p>"},"comercial":{"1":"<p>Room Upgrades: One Upgrade to the\\n  next room category available&nbsp;for every&nbsp;@COMPS@&nbsp;rooms paid&nbsp;cumulative basis  nightly.&nbsp;2 guests maximum. Maximum&nbsp;@MAXCOMPS@ upgrades.&nbsp;\\n  Additional nights will be at the group rates.</p>"}}'
	WHERE idbnf_configuracion_clausula=9;
UPDATE clv_benefits.bnf_configuracion_clausula
	SET texto='{"legal":{"1":"<p>pendiente</p>"},"comercial":{"1":"<p>pendiente</p>"}}'
	WHERE idbnf_configuracion_clausula=10;
UPDATE clv_benefits.bnf_configuracion_clausula
	SET texto='{"legal":{"1":"<p>The Company will cause the Hotel to provide a @GOLF%@% discount on\\n  Green Fees at Moon Palace Golf course. Discount does not apply to twilight\\n  rate, equipment rental or pro shop. Delete if offering Resort Credit.</p>"},"comercial":{"1":"<p>Golf Discount: Group will get @GOLF%@%\\n  discount on green fees at Moon Palace Golf course.&nbsp;Does not apply to\\n  twilight rate, equipment rental, pro shop or other promotions.</p>"}}'
	WHERE idbnf_configuracion_clausula=11;
UPDATE clv_benefits.bnf_configuracion_clausula
	SET texto='{"legal":{"1":"<p>The Company will cause the Hotel to provide a @SPA%@% discount on\\n  Spa treatments. Does not apply to discounted packages. Not applicable if receiving Resort Credit.</p>"},"comercial":{"1":"<p>Spa Discount: Group will get @SPA%@%\\n  discount on Spa treatments. Does not apply to discounted packages or other\\n  promotions.</p>"}}'
	WHERE idbnf_configuracion_clausula=12;
UPDATE clv_benefits.bnf_configuracion_clausula
	SET texto='{"legal":{"1":"<p>The Company will cause the Hotel to apply @MASTERACCOUNT%@% of the total\\n  Net Room Pickup towards incidental charges billed to the master account. Net\\n  Room Pick up is defined as the total room revenue picked up less\\n  complimentary and staff rooms and after the deduction of taxes and\\n  gratuities. The credit may not be used towards reducing room revenue owed or\\n  towards any applicable liquidated damages. Credit may be used towards\\n  surcharges for private receptions in suites, tee times at Moon Palace Spa\\n  &amp; Golf Club, Spa treatments at any Palace Resort, Palace Productions AV\\n  &amp; décor services. Not applicable for any cost established in the Palace\\n  Production Technical Production Manual, nor for any cost derivative from any\\n  external supplier. No cash reimbursement if credit is not used. Unused Credit\\n  cannot be applied to future programs.<br><br></p>"},"comercial":{"1":"<p>Credit Back to the Group Master Account: Group will get @MASTERACCOUNT%@% of the total net group amount, credited back to the Group Master account. The credit is applicable towards surcharges for private receptions in suites, Golf at Moon Palace Spa &amp; Golf Club, Spa services at any Palace Resort or Palace Productions AV &amp; Décor services, Transportation services when contracting all Group transfers through GDS DMC, Upgraded hotel amenities and much more!</p>"}}'
	WHERE idbnf_configuracion_clausula=13;
UPDATE clv_benefits.bnf_configuracion_clausula
	SET texto='{"legal":{"1":"<p>The Company will cause the Hotel to offer a special amenity of\\n  $500 Resort Credit (for 3 nights) or $750 Resort Credit (for 4 nights) or\\n  $1,500 Resort Credit (for 5 to 8 nights). Credit is based on per room per\\n  stay and it is only applicable to individual guest room folio. Resort credit\\n  is non-transferable and non-cumulative. Resort Credit has no commercial value\\n  and is not subject to refund or credit. 16% Taxes and fees apply for services\\n  redeemed and will be covered by each guest.Terms and condition at_______________<br><br></p>"},"comercial":{"1":"<p>Resort Credit: Up to $1,500 USD in Resort Credit per room that\\n  may be used towards Golf reservations, Spa Services, Selected Tours, Family\\n  photo sessions, Gastronomic Experiences and selected items at the Hotel’s\\n  Gift Shop and Jewellery Store. 16% Taxes and fees are applicable for services\\n  redeemed. Terms and condition at_______________</p>"}}'
	WHERE idbnf_configuracion_clausula=14;
UPDATE clv_benefits.bnf_configuracion_clausula
	SET texto='{"legal":{"1":"<p>The Company will cause the Hotel to offer a special amenity of\\n  $500 Resort Credit (for 3 nights) or $750 Resort Credit (for 4 nights) or\\n  $1,500 Resort Credit (for 5 to 8 nights). Credit is based on per room per\\n  stay and it is only applicable to individual guest room folio. Resort credit\\n  is non-transferable and non-cumulative. Resort Credit has no commercial value\\n  and is not subject to refund or credit. 16% Taxes and fees apply for services\\n  redeemed and will be covered by each guest.Terms and condition at_______________</p>"},"comercial":{"1":"<p>Resort Credit: Up to $1,500 USD in Resort Credit per room that\\n  may be used towards Golf reservations, Spa Services, Selected Tours, Family\\n  photo sessions, Gastronomic Experiences and selected items at the Hotel’s\\n  Gift Shop and Jewellery Store. 16% Taxes and fees are applicable for services\\n  redeemed. Terms and condition at_______________</p>"}}'
	WHERE idbnf_configuracion_clausula=15;
UPDATE clv_benefits.bnf_configuracion_clausula
	SET texto='{"legal":{"1":"<p>The Company will cause the Hotel to provide a maximum of&nbsp;@VIPSTATUS@ VIP status with 50 minutes spa treatments included.</p>"},"comercial":{"1":"<p>A maximum of\\n@VIPSTATUS@&nbsp;VIP status with 50 minutes spa treatments included.</p>"}}'
	WHERE idbnf_configuracion_clausula=16;
UPDATE clv_benefits.bnf_configuracion_clausula
	SET texto='{"legal":{"1":"<p>@OPTIONAL@</p>"},"comercial":{"1":"<p>@OPTIONAL@</p>"}}'
	WHERE idbnf_configuracion_clausula=17;
UPDATE clv_benefits.bnf_configuracion_clausula
	SET texto='{"legal":{"1":"<p>Free Kids Promotion: Children up to 17 years old are free of\\n  charge when sharing a room with their parents.</p>"},"comercial":{"1":"<p>Free Kids Promotion: Children up to 17 years old are free of\\n  charge when sharing a room with their parents.</p>"}}'
	WHERE idbnf_configuracion_clausula=18;
UPDATE clv_benefits.bnf_configuracion_clausula
	SET texto='{"legal":{"1":"<p>Ready, Sell, Stay!: Our Rewards Program to thank you for your\\n  preference by earning Complimentary nights at any Palace Resorts property\\n  when booking a group with us. For detailed information please visit the\\n  attached web link.______</p>"},"comercial":{"1":"<p>Ready, Sell, Stay!: Our Rewards Program to thank you for your\\n  preference by earning Complimentary nights at any Palace Resorts property\\n  when booking a group with us. For detailed information please visit the\\n  attached web link._____</p>"}}'
	WHERE idbnf_configuracion_clausula=19;
