# -*- coding: utf-8 -*-
"""
    models.region
    ~~~~~~~~~~~~~~

    Autogenerated model 'RegionModel'

    :copyright: (c) 2019 by Software Clever, Palace Resorts CEDIS.
    :author: lresendiz
    :author: ixicale
    :license: Private.
"""

from config import db
from sqlalchemy import Column
from sqlalchemy.dialects.mysql import INTEGER, VARCHAR
from models.base_model import BaseModel

__all__ = ["RegionModel"]


#: Marshmallow Rules
def get_info(column):
    cols = {
        "iddef_region": dict(required=True),
        "nombre": dict(required=True),
        "iddef_negocio": dict(required=True),
    }
    return dict(marshmallow=cols[column])


class RegionModel(BaseModel, db.Model):

    __tablename__ = "def_region"

    iddef_region = Column(
        INTEGER(11), primary_key=True, info=get_info("iddef_region")
    )
    nombre = Column(VARCHAR(45), info=get_info("nombre"))
    iddef_negocio = Column(INTEGER(11), info=get_info("iddef_negocio"))
