# -*- coding: utf-8 -*-
"""
    resources.region
    ~~~~~~~~~~~~~~

    Autogenerated endpoints to 'region' model

    :copyright: (c) 2019 by Software Clever, Palace Resorts CEDIS.
    :author: lresendiz
    :author: ixicale
    :license: Private.
"""
from config import api
from .region import Region, Regions, RegionsFilters

api.add_resource(Region, "/region/<int:id>")
api.add_resource(Regions, "/region")
api.add_resource(RegionsFilters, "/regionby")
